version: '3.8'

services:
  httpbin:
    image: kennethreitz/httpbin
    ports:
      - "80:80"
    network_mode: host

  redis:
    image: "redis:latest"
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server"]
    ports:
      - "6379:6379"
    network_mode: host

  kong-api-gateway:
    build: ./kong-api-gateway
    environment:
      - KONG_DATABASE=off
      - KONG_HEADER=my_head
      - KONG_DECLARATIVE_CONFIG=/kong/config.yml
      # Plugin configuration      
      - KONG_PLUGINS=bundled,pangea-connect
      - KONG_PLUGINSERVER_NAMES=pangea-connect
      - KONG_PLUGINSERVER_PANGEA_CONNECT_START_CMD=/kong/go-plugins/pangea-connect
      - KONG_PLUGINSERVER_PANGEA_CONNECT_QUERY_CMD=/kong/go-plugins/pangea-connect -dump
      - KONG_NGINX_MAIN_ENV=PANGEA_IP_INTEL_TYPE;env PANGEA_INTEL_TOKEN;env PANGEA_DOMAIN;env PANGEA_ENABLED;env PANGEA_IP_INTEL_SCORE_THRESHOLD;env REDIS_URL;env REDIS_PASSWORD;env REDIS_TTL"
      - PANGEA_INTEL_TOKEN=$PANGEA_INTEL_TOKEN
      - PANGEA_DOMAIN=$PANGEA_DOMAIN
      - PANGEA_ENABLED=$PANGEA_ENABLED
      - PANGEA_IP_INTEL_TYPE=$PANGEA_IP_INTEL_TYPE
      - PANGEA_IP_INTEL_SCORE_THRESHOLD=$PANGEA_IP_INTEL_SCORE_THRESHOLD
      - REDIS_URL=$REDIS_URL
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_TTL=$REDIS_TTL

    volumes:
      - ./kong-api-gateway/config.yml:/kong/config.yml
    ports:
      - '8000:8000'
      - '8001:8001'
      - '8443:8443'
      - '8444:8444'
    network_mode: host
    depends_on:
      - redis
      - httpbin

  krakend-api-gateway:
    image: devopsfaith/krakend:latest
    ports:
      - "8080:8080"
    environment:
      - PANGEA_INTEL_TOKEN=$PANGEA_INTEL_TOKEN
      - PANGEA_DOMAIN=$PANGEA_DOMAIN
      - PANGEA_IP_INTEL_TYPE=$PANGEA_IP_INTEL_TYPE
      - PANGEA_IP_INTEL_SCORE_THRESHOLD=$PANGEA_IP_INTEL_SCORE_THRESHOLD
      - REDIS_URL=$REDIS_URL
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_TTL=$REDIS_TTL
    volumes:
      - ./krakend-api-gateway/krakend.json:/etc/krakend/krakend.json
      - ./krakend-api-gateway/krakend_extra_config:/etc/krakend/krakend_extra_config
      - ./krakend-api-gateway/plugin/krakend-pangea-connect.so:/opt/krakend/plugin/krakend-pangea-connect.so
    network_mode: host
    depends_on:
      - httpbin
      - redis

  gin-gonic:
    build: ./gin-gonic
    environment:
      - PANGEA_INTEL_TOKEN=$PANGEA_INTEL_TOKEN
      - PANGEA_DOMAIN=$PANGEA_DOMAIN
      - PANGEA_IP_INTEL_TYPE=$PANGEA_IP_INTEL_TYPE
      - PANGEA_IP_INTEL_SCORE_THRESHOLD=$PANGEA_IP_INTEL_SCORE_THRESHOLD
      - REDIS_URL=$REDIS_URL
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_TTL=$REDIS_TTL
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - redis

  gofiber:
    build: ./gofiber
    environment:
      - PANGEA_INTEL_TOKEN=$PANGEA_INTEL_TOKEN
      - PANGEA_DOMAIN=$PANGEA_DOMAIN
      - PANGEA_IP_INTEL_TYPE=$PANGEA_IP_INTEL_TYPE
      - PANGEA_IP_INTEL_SCORE_THRESHOLD=$PANGEA_IP_INTEL_SCORE_THRESHOLD
      - REDIS_URL=$REDIS_URL
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_TTL=$REDIS_TTL
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - redis

  spring-api-gateway:
    build: ./spring-api-gateway
    environment:
      - PANGEA_INTEL_TOKEN=$PANGEA_INTEL_TOKEN
      - PANGEA_DOMAIN=$PANGEA_DOMAIN
      - PANGEA_IP_INTEL_TYPE=$PANGEA_IP_INTEL_TYPE
      - PANGEA_IP_INTEL_SCORE_THRESHOLD=$PANGEA_IP_INTEL_SCORE_THRESHOLD
      - REDIS_URL=$REDIS_URL
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_TTL=$REDIS_TTL
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - httpbin
      - redis

  spring-boot:
    build: ./spring-boot
    environment:
      - PANGEA_INTEL_TOKEN=$PANGEA_INTEL_TOKEN
      - PANGEA_DOMAIN=$PANGEA_DOMAIN
      - PANGEA_IP_INTEL_TYPE=$PANGEA_IP_INTEL_TYPE
      - PANGEA_IP_INTEL_SCORE_THRESHOLD=$PANGEA_IP_INTEL_SCORE_THRESHOLD
      - REDIS_URL=$REDIS_URL
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_TTL=$REDIS_TTL
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - redis

  spring-webflux:
    build: ./spring-webflux
    environment:
      - PANGEA_INTEL_TOKEN=$PANGEA_INTEL_TOKEN
      - PANGEA_DOMAIN=$PANGEA_DOMAIN
      - PANGEA_IP_INTEL_TYPE=$PANGEA_IP_INTEL_TYPE
      - PANGEA_IP_INTEL_SCORE_THRESHOLD=$PANGEA_IP_INTEL_SCORE_THRESHOLD
      - REDIS_URL=$REDIS_URL
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_TTL=$REDIS_TTL
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - redis

  quarkus:
    build: ./quarkus
    environment:
      - PANGEA_INTEL_TOKEN=$PANGEA_INTEL_TOKEN
      - PANGEA_DOMAIN=$PANGEA_DOMAIN
      - PANGEA_IP_INTEL_TYPE=$PANGEA_IP_INTEL_TYPE
      - PANGEA_IP_INTEL_SCORE_THRESHOLD=$PANGEA_IP_INTEL_SCORE_THRESHOLD
      - REDIS_URL=$REDIS_URL
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_TTL=$REDIS_TTL
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - redis

  expressjs:
    build: ./expressjs
    environment:
      - PANGEA_INTEL_TOKEN=$PANGEA_INTEL_TOKEN
      - PANGEA_DOMAIN=$PANGEA_DOMAIN
      - PANGEA_IP_INTEL_TYPE=$PANGEA_IP_INTEL_TYPE
      - PANGEA_IP_INTEL_SCORE_THRESHOLD=$PANGEA_IP_INTEL_SCORE_THRESHOLD
      - REDIS_URL=$REDIS_URL
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_TTL=$REDIS_TTL
    ports:
      - "8080:8080"
    network_mode: host
    depends_on:
      - redis
