spring:
  application:
    name: spring-boot-starter-pangea-connect
  data:
    redis:
      connection: redis://localhost:6379
      connection-timeout: 2000
  config:
    activate:
      on-profile: default

pangea:
  token: ${PANGEA_INTEL_TOKEN}
  domain: ${PANGEA_DOMAIN}
  ip-intel:
    enabled: true
    type: ${PANGEA_IP_INTEL_TYPE}
    score-threshold: ${PANGEA_IP_INTEL_SCORE_THRESHOLD}
